title: Deadlines # (Forked from @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns
author: Abhishek Das

domain: "ai-deadlines.github.io/amirziai"
baseurl: ""

markdown: kramdown
ga_id: UA-36274081-2
