title: Deadlines # (Forked from @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to deadlines
author: Abhishek Das

domain: "ai-deadlines.github.io/amirziai"
baseurl: ""

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: abhshkdz
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2
